# fly.toml app configuration file generated for r2d2wm-bot on 2024-07-06T13:47:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'r2d2wm-bot'
primary_region = 'cdg'

[build]

[http_service]
min_machines_running = 1
processes = ['app']

[env]
RUST_LOG = "warn,r2d2wm_bot=trace"
DATA_PATH = "/config"
TIMEZONE = "Europe/Paris"

[mounts]
source = "data"
destination = "/config"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
