# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'r2d2wm-bot'
primary_region = 'cdg'

[build]

[processes]
bot = "/usr/local/bin/r2d2wm-bot"
api = "/usr/local/bin/r2d2wm-api"

[http_service]
processes = ["api"]
auto_start_machines = true
auto_stop_machines = true
min_machines_running = 0

[env]
RUST_LOG = "warn,r2d2wm_bot=trace"
DATA_PATH = "/config"
TIMEZONE = "Europe/Paris"

[[mounts]]
source = "data"
destination = "/config"

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1