name: Build and Test

on:
  push:
    branches:
      - 'devel'
      - 'main'
  pull_request:
    branches:
      - 'main'
      - 'devel'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run clippy
        run: cargo clippy -- -Dwarnings
      - name: Run tests
        run: cargo test --verbose